server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Student
    username: postgres
    password: 369silent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true